### ISSUE TITLE
consider setting global/body font size based on `text-base`

### ISSUE THREAD

**Issue by montchr** [kleinweb/logan-center#43]
a lot of repetition of `.text-base` is necessary since the default 16px font size won't work so well with URW DIN. does it make sense to adjust globally? would that cause a ripple effect of necessary spacing adjustments everywhere?

**Comment by bpizzle** [comment]
could you clarify what size were you thinking of changing it to?

**Comment by montchr** [comment]
@bpizzle this is more of a technical implementation question about how best to leverage Tailwind. one of the anti-goals here would be to preserve the visual appearance -- this would be a refactor, not a visual design change.
